GET http://localhost:8080/api/answers/A01741437/surveyQuestions/4

###
POST http://localhost:8080/api/answers/A01741437/surveyQuestions/10
content-type: application/json

{
    "targetKind": "CRN",
    "teacherRegistration": null,
    "crn": 2,
    "content": "9"
}