INSERT INTO Course VALUES
(1, 'TC2005B', 'Construcción de software y toma de decisiones', 'BLOCK'),
(2, 'AG2001B', 'Análisis de biosistemas productivos', 'BLOCK'),
(3, 'AG2029', 'Fundamentación de biosistemas productivos', 'COURSE'),
(4, 'BI2001B', 'Diseño de sistemas de bioinstrumentación analógica', 'BLOCK'),
(5, 'BI2002B', 'Diseño de sistemas de bioinstrumentación digital', 'BLOCK'),
(6, 'BI2003B', 'Análisis químico, biológico y molecular', 'BLOCK'),
(7, 'BI2007B', 'Análisis de sistemas de imagenología', 'BLOCK'),
(8, 'BI2008B', 'Aplicación de la Ingeniería tisular y bioimpresión', 'BLOCK'),
(9, 'BI2009B', 'Procesamiento de imágenes médicas para el diagnóstico', 'BLOCK'),
(10, 'BI2010B', 'Diseño y desarrollo en neuroingeniería', 'BLOCK'),
(11, 'BI2011', 'Aplicación de tecnologías de la información en salud', 'COURSE'),
(12, 'BI2011B', 'Implementación de ingeniería clínica', 'BLOCK'),
(13, 'BI2012', 'Caracterización de biomateriales', 'COURSE'),
(14, 'BI2012B', 'Análisis de la mecánica de biofluidos', 'BLOCK'),
(15, 'BT1013', 'Análisis de biología computacional', 'COURSE'),
(16, 'BT1014', 'Fundamentación de la biología molecular', 'COURSE'),
(17, 'BT2002B', 'Elaboración de productos biotecnológicos', 'BLOCK'),
(18, 'BT2006B', 'Diseño de biorreactores', 'BLOCK'),
(19, 'BT2019', 'Análisis y estudio de biosistemas', 'COURSE'),
(20, 'CV1010', 'Fundamentos de geología aplicada al ambiente construido', 'COURSE'),
(21, 'CV1011', 'Evaluación del impacto ambiental de proyectos territoriales', 'COURSE'),
(22, 'CV2001B', 'Análisis de la interacción del ambiente construido y el entorno', 'BLOCK'),
(23, 'CV2002B', 'Evaluación del comportamiento de materiales en estructuras', 'BLOCK'),
(24, 'CV2007B', 'Modelación de técnicas de saneamiento del agua', 'BLOCK'),
(25, 'CV2008B', 'Diseño de movilidad eficiente de personas y mercancías', 'BLOCK'),
(26, 'CV2009B', 'Diseño estructural con concreto reforzado y acero', 'BLOCK'),
(27, 'CV2035', 'Modelación de la información en la construcción', 'COURSE'),
(28, 'CV2036', 'Gestión de costos', 'COURSE'),
(29, 'CV2037', 'Planeación y control de obra', 'COURSE'),
(30, 'DS2002B', 'Implementación de programas de manejo de recursos', 'BLOCK'),
(31, 'DS3002B', 'Economía circular, materiales y procesos sustentables', 'BLOCK'),
(32, 'F1001B', 'Modelación de la ingeniería y ciencias', 'BLOCK'),
(33, 'F1008', 'Experimentación física y pensamiento estadístico', 'COURSE'),
(34, 'F1010B', 'Aplicación de la termodinámica en ingeniería de procesos', 'BLOCK'),
(35, 'F1013', 'Introducción a la modelación del movimiento', 'COURSE'),
(36, 'F1013B', 'Modelación computacional de sistemas eléctricos', 'BLOCK'),
(37, 'F1015B', 'Aplicación de la termodinámica en sistemas ingenieriles', 'BLOCK'),
(38, 'F1018B', 'Aplicación de la termodinámica en ciencias', 'BLOCK'),
(39, 'F1021B', 'Ciencia, tecnología y sociedad', 'BLOCK'),
(40, 'F2002B', 'Solución de problemas de mecánica clásica', 'BLOCK'),
(41, 'F2003B', 'Modelación numérica de sistemas físicos determinísticos', 'BLOCK'),
(42, 'F2004B', 'Aplicación de las fuentes alternas de energía', 'BLOCK'),
(43, 'F2005B', 'Análisis de fenómenos ópticos', 'BLOCK'),
(44, 'F2008B', 'Caracterización experimental de sistemas ópticos', 'BLOCK'),
(45, 'F2009B', 'Caracterización experimental de materiales', 'BLOCK'),
(46, 'IN2001B', 'Desarrollo de proyectos con visión sistémica', 'BLOCK'),
(47, 'IN2002B', 'Mejora de un proceso organizacional con métodos estadísticos', 'BLOCK'),
(48, 'IN2003B', 'Conceptualización de procesos con enfoque innovador', 'BLOCK'),
(49, 'IN2004B', 'Generación de valor con analítica de datos', 'BLOCK'),
(50, 'IN2005B', 'Evaluación de la competitividad organizacional', 'BLOCK'),
(51, 'IN2007B', 'Diseño disruptivo de procesos organizacionales', 'BLOCK'),
(52, 'IN2008B', 'Aseguramiento de la excelencia operacional', 'BLOCK'),
(53, 'IN2009B', 'Mejora de una cadena de valor adaptativa', 'BLOCK'),
(54, 'IN2032', 'Análisis estadístico de datos', 'COURSE'),
(55, 'IN2037', 'Diseño de sistemas ciberfísicos', 'COURSE'),
(56, 'IN2038', 'Evaluación económica de proyectos', 'COURSE'),
(57, 'IN2039', 'Visualización de datos para la toma de decisiones', 'COURSE'),
(58, 'IN2041', 'Mejora de procesos con métodos heurísticos y metaheurísticos', 'COURSE'),
(59, 'IN2042', 'Modelación de la cadena de valor', 'COURSE'),
(60, 'IN2043', 'Simulación discreta, continua y por agentes', 'COURSE'),
(61, 'IN2044', 'Diseño de un proceso de consultoría y gestión del cambio', 'COURSE'),
(62, 'IN3002B', 'Organizaciones resilientes', 'BLOCK'),
(63, 'IN3003B', 'Administración profesional y ágil de proyectos', 'BLOCK'),
(64, 'IN3004B', 'Planeación estratégica: de la visión a la acción', 'BLOCK'),
(65, 'IQ2007B', 'Diseño de sistemas de flujo de fluidos', 'BLOCK'),
(66, 'IQ2009', 'Análisis termodinámico de procesos energéticos', 'COURSE'),
(67, 'M2005', 'Análisis  de mecanismos', 'COURSE'),
(68, 'M2006B', 'Diseño de máquinas térmicas', 'BLOCK'),
(69, 'M2033', 'Análisis de esfuerzos y deformaciones', 'COURSE'),
(70, 'MA1024', 'Pensamiento matemático II', 'COURSE'),
(71, 'MA1027', 'Razonamiento matemático', 'COURSE'),
(72, 'MA1031', 'Análisis estadístico', 'COURSE'),
(73, 'MA1033', 'Análisis de ecuaciones diferenciales', 'COURSE'),
(74, 'MA1034', 'Modelación de procesos mediante algebra lineal', 'COURSE'),
(75, 'MA1049', 'Herramientas básicas para la modelación de situaciones reales', 'COURSE'),
(76, 'MA2001B', 'Optimización determinista', 'BLOCK'),
(77, 'MA2002B', 'Análisis de criptografía y seguridad', 'BLOCK'),
(78, 'MA2012', 'Fundamentos de estadística', 'COURSE'),
(79, 'MR2003B', 'Integración mecatrónica', 'BLOCK'),
(80, 'MR2022', 'Análisis de elementos de la mecatrónica', 'COURSE'),
(81, 'MR2024', 'Diseño mecatrónico', 'COURSE'),
(82, 'MR3001B', 'Diseño y desarrollo de robots', 'BLOCK'),
(83, 'MR3003B', 'Emprendimiento tecnológico', 'BLOCK'),
(84, 'MT1011', 'Estrategias de mercado y diferenciación', 'COURSE'),
(85, 'NT2001', 'Diseño de dispositivos nanotecnológicos', 'COURSE'),
(86, 'NT2001B', 'Fabricación de nanoestructuras por métodos químicos', 'BLOCK'),
(87, 'NT2002', 'Generación de prototipos y escalamiento de procesos', 'COURSE'),
(88, 'NT2002B', 'Fabricación de nano y microestructuras por métodos físicos', 'BLOCK'),
(89, 'NT2004B', 'Aplicación de nanodispositivos en soluciones integrales', 'BLOCK'),
(90, 'NT2005B', 'Aplicación de prototipado y escalamiento en soluciones integrales', 'BLOCK'),
(91, 'Q1021', 'Experimentación química y pensamiento estadístico fundamental', 'COURSE'),
(92, 'Q1022', 'Análisis de la transformación de la materia en procesos químicos', 'COURSE'),
(93, 'Q1028', 'Fundamentación de la estructura y transformación de la materia', 'COURSE'),
(94, 'Q2001B', 'Fundamentación fisicoquímica de las propiedades de las nanoestructuras', 'BLOCK'),
(95, 'Q2003B', 'Aplicación de investigación en soluciones integrales', 'BLOCK'),
(96, 'Q2027', 'Investigación y diseño experimental', 'COURSE'),
(97, 'TA2001B', 'Diseño de alimentos saludables', 'BLOCK'),
(98, 'TA2017', 'Diseño sustentable en procesamiento de alimentos', 'COURSE'),
(99, 'TA3003B', 'Desarrollo sustentable de alimentos saludables y personalizados I', 'BLOCK'),
(100, 'TC1002B', 'Herramientas tecnológicas para las ciencias sociales', 'BLOCK'),
(101, 'TC1003B', 'Modelación de la ingeniería con matemática computacional', 'BLOCK'),
(102, 'TC1027', 'Programación para negocios', 'COURSE'),
(103, 'TC1030', 'Programación orientada a objetos', 'COURSE'),
(104, 'TC1033', 'Pensamiento computacional orientado a objetos', 'COURSE'),
(105, 'TC2004B', 'Análisis de ciencia de datos', 'BLOCK'),
(106, 'TC2006B', 'Interconexión de dispositivos', 'BLOCK'),
(107, 'TC2008B', 'Modelación de sistemas multiagentes con gráficas computacionales', 'BLOCK'),
(108, 'TC2032', 'Diseño de agentes inteligentes', 'COURSE'),
(109, 'TC2033', 'Análisis de sistemas basados en conocimiento', 'COURSE'),
(110, 'TC2034', 'Modelación del aprendizaje con inteligencia artificial', 'COURSE'),
(111, 'TC3004B', 'Planeación de sistemas de software', 'BLOCK'),
(112, 'TE1020', 'Análisis de circuitos eléctricos', 'COURSE'),
(113, 'TE2001B', 'Caracterización experimental mediante instrumentación electrónica', 'BLOCK'),
(114, 'TE2002B', 'Diseño con lógica programable', 'BLOCK'),
(115, 'TE2005B', 'Aplicación de la teoría electromagnética', 'BLOCK'),
(116, 'TE2010B', 'Desarrollo de sistemas de procesamiento digital de señales', 'BLOCK'),
(117, 'TE2044', 'Fundamentación electrónica', 'COURSE'),
(118, 'TE2047', 'Análisis de circuitos eléctricos de corriente alterna', 'COURSE'),
(119, 'TE3001B', 'Fundamentación de robótica', 'BLOCK'),
(120, 'TI1015', 'Análisis de requerimientos de software', 'COURSE'),
(121, 'TI2002B', 'Evaluación de arquitecturas empresariales', 'BLOCK'),
(122, 'TI2016', 'Estructuras de información', 'COURSE'),
(123, 'TI3001B', 'Administración estratégica y gobierno de tecnologías de información', 'BLOCK'),
(124, 'TI3001C', 'Analítica de datos y herramientas de inteligencia artificial I', 'CONCENTRATION'),
(125, 'TI3005B', 'Trasformación digital de organizaciones de la sociedad civil', 'BLOCK');