INSERT INTO Survey VALUES (NULL, "Mi primera encuesta", CURDATE() - INTERVAL 8 DAY, CURDATE() - INTERVAL 7 DAY);
INSERT INTO Survey VALUES (NULL, "Mi segunda encuesta", CURDATE() - INTERVAL 6 DAY, CURDATE() - INTERVAL 5 DAY);
INSERT INTO Survey VALUES (NULL, "Mi tercera encuesta", CURDATE(), CURDATE() + INTERVAL 2 DAY);
INSERT INTO Survey VALUES (NULL, "Mi cuarta encuesta", CURDATE() + INTERVAL 3 DAY, CURDATE() + INTERVAL 4 DAY);